base_model: stabilityai/stablelm-2-1_6b
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

chat_template: chatml

datasets:
  - path: /workspace/filosofia_sharegpt.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/merged_canzoni.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/merged_movies.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/neural_story_anthropic_final.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/translated_samantha1.5_cleaned.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/wikipedia_qa_gpt.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/Samantha2.0-eng.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml

dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/out

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

adapter:
lora_model_dir:
lora_r:
lora_alpha:
lora_dropout:
lora_target_linear:
lora_fan_in_fan_out:

wandb_project: StableLM
wandb_entity: 
wandb_watch:
wandb_name: Samantha2.0-StableLM2-1.6B
wandb_log_model: 

hub_model_id: Samantha2.0-StableLM2-1.6B
save_safetensors: true

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
flash_attn_cross_entropy: false
flash_attn_rms_norm: true
flash_attn_fuse_qkv: false
flash_attn_fuse_mlp: true

warmup_steps: 100
evals_per_epoch: 4
eval_table_size:
saves_per_epoch: 1
save_total_limit: 1
debug:
deepspeed: #deepspeed_configs/zero2.json # multi-gpu only
weight_decay: 0.1
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|endoftext|>
