base_model: stabilityai/stablelm-2-1_6b
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
trust_remote_code: true

load_in_8bit: true
load_in_4bit: false
strict: false

chat_template: chatml

datasets:
  - path: /workspace/datasets/filosofia_sharegpt.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/datasets/merged_canzoni.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/datasets/merged_movies.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/datasets/neural_story_anthropic_final.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/datasets/translated_samantha1.5_cleaned.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml
  - path: /workspace/datasets/wikipedia_qa_gpt.jsonl
    type: sharegpt
    field: conversations
    conversation: chatml

dataset_prepared_path: last_run_prepared
val_set_size: 0.05
output_dir: ./outputs/lora-out

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_on_cpu: true

wandb_project: StableLM
wandb_entity: 
wandb_watch:
wandb_name: Samantha2.0-StableLM2-1.6B
wandb_log_model: 

hub_model_id: Samantha2.0-StableLM2-1.6B
save_safetensors: true

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
flash_attn_cross_entropy: false
flash_attn_rms_norm: true

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|endoftext|>